# 開發環境用的 config 設定
debug: true

server:
  port: ${PORT:8080}
  shutdown: graceful
  compression:
    enabled: true

spring:
  application:
    name: springcat
  # deferred 讓 spring boot jpa 再啟動時期, 可以異步掃描 repository 優化啟動速度
  # ref: https://blog.csdn.net/andy_zhang2007/article/details/95774766
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:springcat;MODE=PostgreSQL
  freemarker:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database: h2
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.example.springcat.config.TableNamingStrategyConfig
    open-in-view: false

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace